name: Inspect OIDC Token

# This workflow runs on any push to main, just like the other one.
on:
  push:
    branches:
      - main
  # You can also add workflow_dispatch to run it manually from the Actions tab
  workflow_dispatch:

# We need this permission to request the token from GitHub
permissions:
  id-token: write

jobs:
  inspect-the-token:
    runs-on: ubuntu-latest
    steps:
      - name: Get and Decode OIDC Token
        uses: actions/github-script@v6
        with:
          script: |
            # This requests the OIDC token from GitHub's runtime
            const token = await core.getIDToken();
            
            // The token is a JWT (header.payload.signature)
            // We just need the middle 'payload' part
            const payload = JSON.parse(Buffer.from(token.split('.')[1], 'base64').toString());

            console.log('--- OIDC TOKEN PAYLOAD ---');
            console.log(JSON.stringify(payload, null, 2));
            console.log('--------------------------');
            
            console.log('\n>>> CRITICAL INFORMATION <<<');
            console.log(`The exact 'repository' claim is: ${payload.repository}`);